AWSTemplateFormatVersion: '2010-09-09'
Description: Secure S3 Bucket Example

Resources:
  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-secure-bucket-${AWS::AccountId}-${AWS::Region}" 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256